### ISSUE TITLE
parse_pdf_by_ocr_images is writing data to databse one character per record 

### ISSUE THREAD

**Issue by virunew** [llmware-ai/llmware#307] opened 2024-01-21 11:00 UTC
The problem is with parse_pdf_by_ocr_images()  function.
parse_pdf_by_ocr_images()  calls parse_pdf_by_ocr_images() for writing data to database. .The function parse_pdf_by_ocr_images() expects a list but  parse_pdf_by_ocr_images() provides a string. This causes parse_pdf_by_ocr_images function to breakup the given string into characters and write each character as one record.

I am raising a PR to fix this, please check.

**Comment by doberst** [comment] 2024-01-28 13:13
@virunew - with the fix that you put in last week, our tests are coming up positive on this issue (e.g. not seeing errors) - without the second pull request....    Could you share the document (or a description of the kind of document) that is still producing one character blocks?   (Per your fix last week, I suspect that the problem is in the TextChunker ...)

**Comment by doberst** [comment] 2024-01-28 17:53
@virunew - please ignore my comment from this morning - just found a good example of the problem with one-letter output ....

**Comment by doberst** [comment] 2024-01-28 18:29
Your PR fix is merged and working in our testing ...

**Closed by doberst** 2024-01-28 18:29 UTC
