### ISSUE TITLE
JSON files not being parsed and are being rejected

### ISSUE THREAD

**Issue by indohito** [llmware-ai/llmware#493] opened 2024-03-10 06:53 UTC
The JSON files that I am trying to add to MILVUS vector database are not being added and are instead being rejected by the parser is there any reason for this or any reason why this would be happening?

**Comment by MacOS** [comment] 2024-03-10 11:14
Hi @indohito,

can you please post a self-contained example that reproduces your issue? Thank you!

**Comment by indohito** [comment] 2024-03-11 00:52
Yeah! This is an example:
```
def create_library(library_path, lib_name):
    lib = Library().create_new_library(lib_name)
    print(lib.add_files(library_path))
    embedding_model = "mini-lm-sbert"
    vector_db = "milvus"
    lib.install_new_embedding(embedding_model_name=embedding_model, vector_db=vector_db)
    return lib
```
and this is the output for adding the files:
![image](https://github.com/llmware-ai/llmware/assets/107958888/7bfe0ccf-92a6-4398-b236-3d249a09a646)

**Comment by MacOS** [comment] 2024-03-11 11:33
Thank you for posting this, @indohito! Might I also ask you post a sample of one of your ``json``?

The reason for rejecting is that the library does not have a parser for ``json``. How would you expect such a parser to work?

**Comment by indohito** [comment] 2024-03-13 00:31
ok yeah I figured I was wondering if there was way around this, Probably just a way to extract the metadata fields that are given in the json files

**Comment by MacOS** [comment] 2024-03-13 08:35
What do you mean with a way around this?

Do I understand you correctly, when I say that you want to embed the metadata?

**Comment by doberst** [comment] 2024-03-26 21:24
@indohito - we have made some updates to improve the json file handling, as well as an updated example that can be found [here](https://github.com/llmware-ai/llmware/blob/main/examples/Parsing/parse_jsonl_custom.py)   If you clone the latest code in the repo, it will provide all of the fixes outlined in the example.   Please also note that generally if a JSON file does not include a "text" key attribute, the parser will not know which text to extract from the file in the core text index (which is the main content that is 'parsed.'    Closing this issue - but please raise a new issue if you continue to have any problems wiht this.  Thanks for raising this!

**Closed by doberst** 2024-03-26 21:24 UTC
